export var poetry = [
    "Some of the waves of wanting speak like a child",
    "Shapes of understanding embrace inside the meaning",
    "Under the cover of death the poets vanish",
    "Amongst the shadows of time the old ones turn",
    "In the child of desire the old ones sleep",
    "In the streets of the soul the women turn",
    "Under a cloudless sky of harmony the leaves echo",
    "In the streets of time the poets speak",
    "My mind always strays to waters",
    "Through which came chatting, chatting, chatting",
    "I am shorn of my smelter",
    "Instead I uncovered the damselfish",
    "I felt compelled to sniff the echinoderms",
    "Death shall bring stingrays",
    "I crave the subantarctic, seaward sawmill",
    "And the sealift never gyring",
    "Deep into that darkness draining",
    "Once I sat engaged and draining",
    "I awoke and flung the wave",
    "My passion is the splendid ardour",
    "By the grave I saw the storms",
    "My passion is the early dinner",
    "'Night!' chuckled I, 'Yes night!'",
    "In a kingdom full of causes",
    "Once I sat engaged and winking",
    "Deep into that darkness brining",
    "By the grave I saw the estuaries",
    "My passion is the happy snowmaking",
    "Snow - tormentor of my dreams",
    "Deep into that darkness bamboozling",
    "I heard a happy, pekinese honking",
    "By the grave I saw the birds",
    "I heard a coral, midstream brining",
    "Much I marvelled the skim spinach",
    "An appointment, however hard it tries",
    "I cannot help but stop and look at the salaried employee",
    "To get me wondering if the activity is nonindustrial.",
    "I cannot help but stop and look at the cunning commitment.",
    "Does the employee make you shiver?",
    "goats are exceptionally double-chinned.",
    "Why aren't foals more large?",
    "How happy is the deer fawns!",
    "When I put my finger to the hole they’ve cut for a dimmer switch",
    "it seems I’ve scratched a two-hundred-year-old itch",
    "with a clink and a clink and a clinky-click.",
    "I can taste the small loaf of bread he baked from that whole seed",
    "Books of the Baal Shem Tov, and of his wonders;",
    "The snuff left on this page, now brown and old,",
    "And my tears, too, have stained this heirloomed ground,",
    "A white hair fallen from my father’s beard.",
    "I’m pillowed and padded, pale and puffing",
    "I’ve spent my life in nothing.",
    "Time is white",
    "And meets with sun-lost lip the marsh’s brim.",
    "Late cranes with heavy wing, and lazy flight,",
    "Hushed lie the sedges, and the vapours creep,",
    "And like a spirit, swathed in some soft veil,",
    "Late cranes with heavy wing, and lazy flight,",
    "And like a spirit, swathed in some soft veil,",
    "The pools low lying, dank with moss and mould,",
    "Never seen by waking eyes.",
    "Ever drifting down the stream —",
    "Echoes fade and memories die:",
    "Lingering onward dreamily",
    "Long has paled that sunny sky:",
    "hearken back to breath, or even farther,",
    "wants not to be voice any longer, wants something",
    "rumour of its former life. Sometimes, even",
    "sloped upward like a take-off ramp",
    "because he wasn’t going to get it paralysed or dead.",
    "readiness to enter the earth at the exact spot left",
    "seen earth before there was blood,",
    "She has nowhere to go.",
    "torrential rain, pointing to a whole universe",
    "like rain gurgling down tin eaves – incessant,",
    "after being forced to shut up too long.",
    "like rain gurgling down tin eaves – incessant,",
    "Anxious attendants scurry up and down the aisle",
    "Facing the girl, he ignores them all, as though",
    "His language of gestures and force – lost",
    "slicing Lake Ontario: placid like an eye",
    "Arose the howl of wakened hounds:",
    "All nations striving strong to make",
    "My neighbour Parson Thirdly said,",
    "And many a skeleton shook his head.",
    "they work good in the dark",
    "grammar not being my strong suit",
    "right after you shower",
    "For my surrounding air hath a new lightness;",
    "To sheathe me half in half the things that sheathe her.",
    "Hath of the trees a likeness of the savour:",
    "Nor public men, nor cheering crowds,",
    "My country is Kiltartan Cross,",
    "Convex and fossiled",
    "From sageland, brushland, marshland",
    "Who would have loved you in a day or two.",
    "I, that had been to you, had you remained,",
    "But one more waking from a recurrent dream,",
    "And all my pretty follies flung aside",
    "And given in earnest words I flung in jest;",
    "And walk your memory’s halls, austere, supreme,",
    "Don't drink the water, they put something in it... to make you forget",
    "…ÿrV)Ðµ8[Ûã¸r„D ›9H`§€hwœa„§€ëLzÛ!I@8â4†@âêŸ6,UxUÀáätÏÙ:®–ƒhtÃù-Ç7æHøŠkB$pÁ	vƒE†F9`SXJXUä$ŽVÖi2Ï(«I¼sOášÈ*<Ã‘@‰K,07ë<«²”Â€¦qŒý'-Q„@`2$",
    "IDAT>mHn™=»çŽ:ðÜÙ“•U%íVãs/>’H×‡èùëo_´4VT•Ÿki¬(½pbèà^ŠHh2¥+4C@2ø6ì—V-¿±µ©|Ç¶ÛãMæaŸ=-ÆX_{¾ªüLKcÕÅs'&Œ&°T³›À ñpGiÊÉ",
    "õ›B·Âôœ”?R²~@ž‘Ya¥ÉŒ&‘*‡(´Ûä(¿Â+,n(´.ƒù*s„!³¦Â9ù%¶óò¦$–Læ(™Ç|K @/wíÈùó¦NŸ2fP¿®×èÞ»{^§‚DçÂdÏ®ÙÝ;g&ÓLq‘(Òðdë	°£˜!’TÝ*ƒk,að°)¡P„WádŽ9Â£ò^MÐ%ÆÙ€GtˆÍo",
    "ûŒ×Ðí0IXWƒŠ¦‹~JÓä¤ðDFÄŸfÅCÙ‰p^2šŸˆ¥Ç‹“±¼h(+ÈMDò±œX4-LOæÄ¢©D~2‘-LOå%â™‘p^^J&ü¾ˆ¡'þ´¬X8-ð:-¨+aŸá7*y5Ù«ªT^tÀ!²À]pª©@Å·½,ì¬jb×jB¬½Bv ,I¸ ÈëõîÛ·oÚ´i{öì5jÔ„",
    "n¼ñFžçØ³gO·ÛªêâÅ‹ÇÇw¬]»vÁ‚óçÏß±cÇðáÃW®}útI’ö<üÈ´ë¦®½}Ícî¹ý¶Õ·®^IÇÒº,¨ˆjx5IdÀŠMK™²0•çŽÓEQ¤m(4#à„DRÎêŽ:qÀäÜ¶!óÈp˜ŠèQ¥€©4Å#	@®*¢È†,LÍæÞA	OáºÄ2°5€EàC¤AØ”c@ãY3T)¨+@GÛ';nO±",
    "/©°™16íÜ4¼nˆcØh[$Þ‘HCØèºM½ÿ›ßþî?øÑôôtVãyÃ0Š¢†á8NQ”Œçç2Ùž®îžî‘þžz¥”õ²Ž™5µŠoT<µì*%W©øF=g7ò^½àU²v-ï|»I÷›µb¶VÌæ=+çZYÇ4QÏÔª…l%—s4Í7Íœã2¾¥©…Œ/óœÀñ†s	ÎE†QyŒ²¿· ü~×PðÅïy54¬ÏHA%ÓD¢ ôÇÉ`;SG˜(ñt¤»žé©9µ‚–µ¨Z^ì,)%ŸñtÔS>¾okWÑ¡á¨Á*‡pxda×dˆ&ÒqdØe›3	O«¦°‚C‹ÑÖŠú£Ñ¨+1ÀK(àžÌ:×‡Ç³]6…î¬Ñ“3+¶´%“#$•X’%1U‘’Éd<‡ée-äŒºÙŒ Õ’#	CT¡fk}…|ÞÔAÇW ]xÊ¢ÉL]¢™¢y’D¡T´½-‹",
  ];